[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
composeNav = "2.9.4"
retrofitVersion = "3.0.0"
hiltVersion = "2.51.1"
hiltNavVersion = "1.2.0"
coroutineVersion = "1.10.2"
material3 = "1.3.2"
interceptorVersion = "4.2.0"
multidexVersion = "2.0.1"
coilVersion = "2.0.0"
flowLayoutVersion = "0.36.0"
firebaseBomVersion = "34.3.0"
roomVersion = "2.6.1"
kspVersion = "2.0.21-1.0.27"
materialIconVersion  = "1.5.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-multidex = { group = "androidx.multidex", name = "multidex" , version.ref = "multidexVersion" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose",version.ref = "composeNav" }
androidx-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit",version.ref = "retrofitVersion" }
androidx-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson",version.ref = "retrofitVersion" }
androidx-dagger-hilt = { group = "com.google.dagger", name = "hilt-android",version.ref = "hiltVersion" }
androidx-hilt-nav = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavVersion" }
androidx-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler",version.ref = "hiltVersion" }
androidx-coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core",version.ref = "coroutineVersion" }
androidx-coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android",version.ref = "coroutineVersion" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptorVersion" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilVersion" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "interceptorVersion" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "interceptorVersion" }
androidx-flowLayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "flowLayoutVersion" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common"}
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBomVersion" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-compose-material = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
kotlin-kapt = { id = "kotlin-kapt" }
google-gms  =  {id = "com.google.gms.google-services", version = "4.4.3"}
android-room  =  {id = "androidx.room", version.ref = "roomVersion"}
kotlin-ksp  =  {id = "com.google.devtools.ksp", version.ref = "kspVersion"}



